# Generated by Django 5.0.7 on 2024-07-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restiot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='SensorDataPoint',
        ),
    ]
