# Generated by Django 5.0.7 on 2024-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restiot', '0002_rename_sensordata_sensordatapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordatapoint',
            name='sensor_timestamp',
        ),
        migrations.AddField(
            model_name='sensordatapoint',
            name='sensor_generated_timestamp',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sensordatapoint',
            name='sensor_saved_timestamp',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
