# Generated by Django 5.0.7 on 2024-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restiot', '0003_remove_sensordatapoint_sensor_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordatapoint',
            name='sensor_saved_timestamp',
        ),
        migrations.AddField(
            model_name='sensordatapoint',
            name='sensor_created_timestamp',
            field=models.DateTimeField(auto_now_add=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sensordatapoint',
            name='sensor_modified_timestamp',
            field=models.DateTimeField(auto_now=True, max_length=100, null=True),
        ),
    ]
