# Generated by Django 5.0.7 on 2024-08-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restiot', '0006_airdata_airqualitydata_lightdata_particledata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdata',
            options={'verbose_name': 'Air Data', 'verbose_name_plural': 'Air Data'},
        ),
        migrations.AlterModelOptions(
            name='airqualitydata',
            options={'verbose_name': 'Air Quality Data', 'verbose_name_plural': 'Air Quality Data'},
        ),
        migrations.AlterModelOptions(
            name='lightdata',
            options={'verbose_name': 'Light Data', 'verbose_name_plural': 'Light Data'},
        ),
        migrations.AlterModelOptions(
            name='particledata',
            options={'verbose_name': 'Particle Data', 'verbose_name_plural': 'Particle Data'},
        ),
        migrations.AlterModelOptions(
            name='sensordatapoint',
            options={'verbose_name': 'Sensor Data', 'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.AlterModelOptions(
            name='sounddata',
            options={'verbose_name': 'Sound Data', 'verbose_name_plural': 'Sound Data'},
        ),
    ]
