# Generated by Django 5.0.7 on 2024-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restiot', '0008_alter_airdata_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdata',
            name='humidity_unit',
            field=models.CharField(blank=True, choices=[('g/m³', 'g/m³'), ('%', '%'), ('g/kg', 'g/kg')], default='%', max_length=10, null=True),
        ),
    ]
